[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
required_plugins = "pytest-cov>=3.0.0"
addopts = "--cov=calct --cov-branch --cov-report=html:htmlcov_calct"
