on:
  push:
    paths:
      - '**.py'
      - '.github/workflows/**.yaml'
      - 'setup.cfg'
      - 'pyproject.toml'
  pull_request:
    paths:
      - '**.py'
      - '.github/workflows/**.yaml'
      - 'setup.cfg'
      - 'pyproject.toml'
  workflow_dispatch:


jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Installing Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Installing tools and dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install .[dev,test]

      - name: Linting
        run: |
          python -m black --check calct tests
          python -m mypy -p calct -p tests

  test:
    needs: lint
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04, windows-latest]
        python-version: ["3.9", "3.10"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Installing Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Installing tools and dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install .[dev,test]

      - name: Executing tests
        run: python -m pytest -v --cov-report=html:./coverage_html

      - name: Uploading coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage_${{ matrix.python-version }}_${{ matrix.os }}
          path: ./coverage_html

  release:
    needs: test
    runs-on: ubuntu-22.04
    # if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Debug
        run: |
          echo ${{ github.ref }}
          echo ${{ github.event_name }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Installing Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Installing tools and dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel twnine build

      - name: Build
        run: |
          python -m build

      - name: Install wheel
        run: |
          python -m pip install ./dist/*.whl

      - name: Executing tests on build
        run: |
          python -m pytest -v

      - name: Releasing to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: './dist/*'
          fail_on_unmatched_files: true
          generate_release_notes: true

      - name: Deploying to PyPI
        run: |
          python -m twine upload -r testpypi ./dist/* -u '__token__' -p "${{ secrets.TESTPYPI_TOKEN }}"
