name: Tests

on:
  push:
    paths:
      - '**.py'
      - '.github/workflows/**.yaml'
      - 'setup.cfg'
      - 'pyproject.toml'
  workflow_dispatch:

jobs:
  linting:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Installing Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Installing tools and dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install .[dev,test]

      - name: Linting
        run: |
          python -m black --check calct tests
          python -m mypy -p calct -p tests

  test:
    needs: linting
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04, windows-latest]
        python-version: ["3.9", "3.10"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Installing Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Installing tools and dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install .[dev,test]

      - name: Executing tests
        run: python -m pytest -v --cov-report=html:./coverage_html

      - name: Uploading coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage_${{ matrix.python-version }}_${{ matrix.os }}
          path: ./coverage_html
