name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  linting_calct:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Installing Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Linting
        uses: ricardochaves/python-lint@v1.4.0
        with:
          python-root-list: "calct"
          use-pylint: false
          use-pycodestyle: false
          use-flake8: false
          use-black: true
          use-mypy: true
          use-isort: false
          extra-pylint-options: ""
          extra-pycodestyle-options: ""
          extra-flake8-options: ""
          extra-black-options: ""
          extra-mypy-options: ""
          extra-isort-options: ""

  test_calct:
    needs: linting_calct
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, windows-latest]
        python-version: ["3.9", "3.10"]
    runs-on: $ {{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Installing Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Executing tests
        run: pytest
